#!/usr/bin/env bash

set -e

cd "$(dirname "$0")"/../

MYPY=(mypy)
RUFF=(ruff)

if [ -x .venv/bin/mypy ]; then
  MYPY=(.venv/bin/mypy)
fi

if [ -x .venv/bin/ruff ]; then
  RUFF=(.venv/bin/ruff)
fi

echo "Running mypy checks..."
"${MYPY[@]}" pdf_tools
"${MYPY[@]}" tests

echo "Running ruff checks..."
"${RUFF[@]}" check pdf_tools --ignore ERA001 --ignore FIX002
"${RUFF[@]}" check tests --ignore ERA001 --ignore FIX002
# ruff check app
"${RUFF[@]}" format pdf_tools --check
"${RUFF[@]}" format tests --check

echo "Linting checks done!"
